### ISSUE TITLE
As a user, I want to have the ability to search in google on keywords so that I can quickly find and navigate to information. 

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#107]
## Notes
- story concentrates on adding metatags for google seo only

## Acceptance Criteria
- [ ] search input located in a global position
- [ ] search results page

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
For this do we want to see if we can just integrate into the broader FS Website search?

**Comment by ASprinkle** [comment]
Closing this ticket - This issue may be addressed at a minimum in the roll out - if the pilot forests include a live link to the christmas tree epermit site on their Forest pages.
