### ISSUE TITLE
As a user, I would like to view detailed maps that display restricted and non-restricted cutting areas.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#135]
## Notes
This comes from the sprint 03 usability test:
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results)

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This will require work on behalf of each pilot forest to build new maps using the same symbol style. It is likely that this would have to be done via a Data Resources Management contract. I am not certain at this point that this is something we will have time to adequately address.  Each map shows the unique information that is necessary to know for each forest.

**Comment by ASprinkle** [comment]
This story is outside of the scope of work for the development team as it requires work from the individual FS offices to develop the maps - and maps are not necessary in all cases.
