### ISSUE TITLE
As a user, I would like to print the maps that are available.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#136]
## Notes
This is an issue identified in the sprint 03 usability testing:
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results)

## Acceptance Criteria
- [ ] map should be legible when printed on A4
- [ ] user should see a button that when clicked opens up the print dialog in the browser

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
I'm not sure how they aren't printable now? They are PDFs that you can print easily from the browser.  Did the user just not understand that they can print that way?

**Comment by ASprinkle** [comment]
I found out from the Flathead and the ARNF that neither forest "requires" the map.  They do advise people that it is up to them to be aware of where they are and the forests offer free MVUM maps or the option to purchase our District maps.  Urban visitors probably really do need the map to find their way in the network of roads and to ensure they are cutting in a legal area. But the map itself is not a required attachment to the Christmas Tree permit.  The Mt. Hood is the same. No maps for Shoshone.

**Comment by ASprinkle** [comment]
Users have the ability to print maps using the menu options from their own computer/browser.
