### ISSUE TITLE
As a user, I would like to find the nearest National Forest from the largest city near me.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#137]
## Notes
This is a suggestion that resulted from the sprint 03 usability testing:
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-03---Christmas-tree-ePermit-research-results)

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Do we still need this story if we have #256?

**Comment by ASprinkle** [comment]
goal already accomplished in the content of the drop down.
