### ISSUE TITLE
As a member of the public (permittee), I can print or acknowledge that I understood the rules and regulations on Christmas tree harvesting in the forest I pick. 

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#15]

**Comment by rrefoy** [comment]
(For example, this guidance will help me understand which areas where cutting is allowed, and other rules I must follow.)

**Comment by hannahkane** [comment]
Is all or part of this issue covered in completed Sprint 5 work?

**Comment by ASprinkle** [comment]
This is being covered in the Permit Design work in the current sprint. Let's verify this during Backlog Refinement meeting on Jan. 3  and close or remove this story is appropriate.

**Comment by sadlerw** [comment]
@ASprinkle @hannahkane I think we can close this right? thanks, Will

**Comment by ASprinkle** [comment]
Yes.
