### ISSUE TITLE
As a user, I want to see a picture of the entire tree and a picture of the needles/branches of the tree so I can better identify it.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#159]
## Notes
This came up in the sprint 04 usability testing
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results)

Some users have suggested having a digital copy of the tree details and images for download to their mobile device so they can use without the need for cell service while in the forest.

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by JaneZC** [comment]
Sample:
![Screen Shot 2017-12-05 at 4.00.55 PM.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/23deb3bd-d6d2-42c5-8d71-45877f5aff76)

Sample Taken From This Brochure:
[https://app.zenhub.com/files/106473503/e4a77c05-6951-481e-9f27-b0c1bd712b48/download](https://app.zenhub.com/files/106473503/e4a77c05-6951-481e-9f27-b0c1bd712b48/download)

**Comment by ASprinkle** [comment]
Closing - low priority on usability and this story is not a priority for MVP.
