### ISSUE TITLE
As a user, I would like to see simple text-based instructions or graphics so that I can properly measure tree diameters and heights when in the forest.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#160]
## Notes
This came from the sprint 04 usability testing summary
[https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results](https://github.com/nciinc/fs-intake-module/wiki/Sprint-04-Christmas-tree-ePermit-research-results)

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The goal of this story is currently being worked on in various other stories (in Sprint 10) that address restructuring the information pages.
