### ISSUE TITLE
As a user I want to be able to see all information regarding cutting hours and dates on the screen without scrolling

### ISSUE THREAD

**Issue by cameronwolf** [nciinc/fs-permit-platform#181]
## Notes
 - "When implementing, recommend placing more weight on the actual dates and times than on the headers (i.e. "Season dates", "Cutting hours")."

## Acceptance Criteria
- [ ] User should be able to see all of the cutting hours and date without scrolling from the top of the "When to cut your tree" section

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by bryanmcfadden** [comment]
Possible design?

![image](https://user-images.githubusercontent.com/16689692/35156336-8de08676-fcfe-11e7-9e92-915b92ecc0d6.png)

**Comment by ASprinkle** [comment]
I recommend closing this story - as the season dates and times are listed at the top of the screen under the "when to cut your tree" section, and we have a story specific to the ARNF that addresses the layout of cutting area dates/times for that forest.

**Comment by ASprinkle** [comment]
This story and #426 are very similar.
