### ISSUE TITLE
As a user, I would like to be able to switch National Forests while on the buy permit page.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#203]
## Notes
This comes from usability testing
[Sprint-05 Christmas tree ePermit research results - December 12, 2017](https://github.com/nciinc/fs-intake-module/wiki/Sprint-05---Christmas-tree-ePermit-research-results---December-12,-2017)

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Closing story -for purposes of the pilot, switching between national forests isn't expected to be a common behavior considering geographical location of pilot forests.
