### ISSUE TITLE
As a user I must be at least 18 years of age to be eligible to purchase a permit

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#21]
Acceptance Criteria

- [ ] age limit of 18 to purchase
- [ ] User agrees that they are 18 years or older on application form
- [ ] Age restriction info for online permit purchasing appears on tree guidelines page.

**Comment by rrefoy** [comment]
Does pay.gov account for this anywhere?

**Comment by MelissaBraxton** [comment]
I think we need to look up CFRs on this. The LEOs I spoke with did not know of any restrictions on who can purchase a permit.

**Comment by JaneZC** [comment]
@MelissaBraxton I've been wondering if this one is dependent upon the forest? For example, 4th graders can get a free permit for a tree. But, some sites say that an adult must accompany the child (and others do not).

In this one - https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fseprd497955.pdf , there's a reference to being 18 years or older to buy a "special products permit," and I think Christmas trees fall under that. 

I'll see if I can dig up the CFR.

**Comment by sadlerw** [comment]
@lauraGgit is there something in the pay.gov docs about this?

**Comment by ASprinkle** [comment]
I am closing this because I haven't been able to find specific information that requires a minimum age restriction in FS Handbooks, CFR or USC or LEO input - we can create a new story later if deemed necessary.
