### ISSUE TITLE
As a user, I would like to read content with consistent headers and accessiblity by having a section on a page by adding a simple component that accepts a heading and a content component.

### ISSUE THREAD

**Issue by sethalt** [nciinc/fs-permit-platform#221]
## Notes
Expand the 'section-heading' component that accepts a 'content' argument. Content would be a separate component.

## Acceptance Criteria
- [ ] pages display as they currently do without using the content input to the section

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by sadlerw** [comment]
According to https://angular.io/guide/component-interaction the only reason to nest components is when they need to share data.  In this case the app-section-heading components don't share any data with the proposed "child" which could be any other component.

I suggest we cancel the issue.  thanks, Will

**Comment by sadlerw** [comment]
@lauraGgit do you have any problems with us closing this?  thanks, Will

**Comment by sethalt** [comment]
I agree with @sadlerw, after a deeper dive, I think this would add un-necessary complexity
