### ISSUE TITLE
As a user, I would like to view a list of National Forests organized by state where I can buy Christmas tree permit.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#256]
## Notes
This comes from the sprint 06 usability testing
[Sprint 06 UT Summary](https://github.com/nciinc/fs-permit-platform/wiki/Sprint-06-Christmas-tree-ePermit-research-results-January-3,-2018)

This lists will benefit people by:
1. Allowing them to view all pilot forests at once
2. Providing links to forests not part of the pilot project

## Acceptance Criteria
- [ ] 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by bryanmcfadden** [comment]
Here is one proposed solution. Using a graphical map offers the following benefits:
1. Requires two clicks to get to a forest. (no text entry searching then selecting)
2. Allows viewing of all forests within a selected state. (state list)
3. Offers a text only version for mobile devices.
4. Allows forests to be added as the come on line in the future without altering design/minimal changes (forests offering Christmas tree permits could be identified with a tree icon or some kind of visual identifier)  

![sp_07_pro_01_01](https://user-images.githubusercontent.com/16689692/34997684-03934512-faab-11e7-91e2-0a3a8c0312be.png)

Screen shown after a state is selected.

![sp_07_pro_01_02](https://user-images.githubusercontent.com/16689692/34997687-04a8f532-faab-11e7-8275-ed87a4cc5fed.png)

**Comment by MelissaBraxton** [comment]
This is interesting, but I think we need to go with something more light weight for this initial pilot (we don't want to presuppose what this should look like when we scale to other forests): 
 - The underlying need is that people want to see where they can cut a tree by state. 
 - Suggest removing the maps from this page and allowing people to select a state via a simple dropdown list to get a list of participating forests within that state.

**Comment by bryanmcfadden** [comment]
Something more like this?

![issue_256](https://user-images.githubusercontent.com/16689692/35006538-da0f476c-fac4-11e7-977f-1df3522b7338.png)

**Comment by sadlerw** [comment]
I wonder if the component at https://www.fs.fed.us/ to find a forest or grassland is something we can borrow/steal?

**Comment by ASprinkle** [comment]
If we can be as consistent as possible on how finding a forest information is presented on this website and other FS websites, that would probably be helpful to the user.

**Comment by ASprinkle** [comment]
No longer needed.
