### ISSUE TITLE
As a user, I would like to see graphics in the 'How to cut your tree' section that show stump height, stump diameter and tree height. 

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#323]
The idea here is to have graphics that match the tree sizes/rules defined on the permit. (max tree height, max stump diameter, max stump height)

Usability testing has shown there is a need for more graphics. Some users have requested graphics (for example, one user suggested a graphic to illustrate tree height)

**Comment by ASprinkle** [comment]
This one seems very similar to story #95.

**Comment by bryanmcfadden** [comment]
@ASprinkle - Good catch! Jane and I looked for this story and apparently missed it.

**Comment by ASprinkle** [comment]
Should this one or 95 be closed or can they be consolidated somehow? do you think it is necessary to have both? It seems that based on past stories, it works well to have a story that is specific to each story when there is a redundant task that needs to occur for each forest's page.

**Comment by bryanmcfadden** [comment]
@ASprinkle @JaneZC - I am OK with closing this one and leaving 95 open. This could be a task under 95 since it is a broader story. What do you think Jane?

**Comment by JaneZC** [comment]
@ASprinkle @bryanmcfadden Agreed.

**Comment by bryanmcfadden** [comment]
Added this as task to [story #95](https://github.com/nciinc/fs-permit-platform/issues/95) and labeled as usability low.
