### ISSUE TITLE
As a user, I need to know whether I can/can't buy a permit for a particular forest before I select a forest, so that I can know whether I can buy my permit now or I need to check back again later.

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#362]
## Notes
- from comments on #102

**Comment by hannahkane** [comment]
Just want to make a note of @ASprinkle's comment during backlog refinement that she liked the look and feel of the [mockup from #102](https://github.com/nciinc/fs-permit-platform/issues/102#issuecomment-360786373) and thought it might be a good solution for this story.

**Comment by sadlerw** [comment]
Do we have usability testing that suggests a need for this @bryanmcfadden ? Looking at the top of the guidelines shows quickly that the season is closed. I'm wondering if people are wanting to really save the click.

**Comment by ASprinkle** [comment]
Closing this story because the Christmas tree season sales dates are visually available at the top of the information page.  It is good to have people be directed to the information pages so that they can choose to learn more about getting a Christmas tree if they want to.
