### ISSUE TITLE
As a user, I would like to be able to see my permits via a login process

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#372]
## Notes
- [ ] logged in users who have also purchased permits (i.e. non-commercial) will be able to use the same login to see purchased tree permits provided the account/email matches.

## Acceptance criteria
- [ ] user should be able to see all purchased permits without having a jwt in the link to authorize them
- [ ] user should be able to know how to get to previously purchased permits without the link in the email (jwt) and that it requires creating an account through login.gov that matches the email used to purchase the permit and then successfully logging in through the forest site.

**Comment by ASprinkle** [comment]
This story would be more valuable for a larger scale, longer term permanent permits solution. For purposes of the Christmas tree pilot, this story is not necessary to meet MVP.
