### ISSUE TITLE
As a user I would like faster load times when visiting the website (remove --aot=false)

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#407]
### Notes
- some work was done on this as part of usual definition of done until it was decided it needed more testing

### Acceptance criteria
- [ ] angular frontend compiles with --prod (ahead of time compile/aot on)
- [ ] all existing functionality including intake works (specs that cover might be necessary)

**Comment by ASprinkle** [comment]
Cannot do with markdown - Melissa is checking in with Laura on this.
