### ISSUE TITLE
As a user, I would like to see a list of vendors for each forest where I can purchase my permit in-person.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-permit-platform#515]
This was brought up in an ADMIN usability test (Shoshone).

**Comment by ASprinkle** [comment]
I wonder some about this - for some forests, a vendors list may not be completed/ready prior to the release of the pilot site. So this is something that would likely be requested for a fix. I wonder if we can't just include a hyperlink to "vendors lists" to a location on the NF website, or include a statement to contact your local office or NF website for information on local vendors...  I see what looks like hyperlinks to vendors in the contact us sections per the mock in story #425

**Comment by JaneZC** [comment]
@ASprinkle I also like the idea of adding a hyperlink to vendors lists stored elsewhere; additionally, sI think at least one forest had a map that incorporated a list of vendors on it.

**Comment by ASprinkle** [comment]
No need to map vendors - too much.

**Comment by ASprinkle** [comment]
Links to vendor information on the NF website are present on the xmas tree e-permits site.
