### ISSUE TITLE
As an FS admin, I need to know that I should be using Google Chrome to operate in the Christmas Tree epermits site.

### ISSUE THREAD

**Issue by ASprinkle** [nciinc/fs-permit-platform#656]
If my understanding is correct, Forest Service employees have to obtain special permissions to install/download Google Chrome.

**Comment by hannahkane** [comment]
@ASprinkle - can you say more about this? Why do admins need to use Chrome?

**Comment by ASprinkle** [comment]
In conversation with @sadlerw it became apparent that some errors admins receive may be occurring because of IE explorer issues - possibly...

**Comment by hannahkane** [comment]
Would like to hear more from @sadlerw. @ASprinkle - I'm not sure how you feel about this, but I would consider it a requirement that the application works in the browser the FS admins typically use.

**Comment by sadlerw** [comment]
It works fine in ie but it makes it harder to use staging without increase incognito due to the eauth sso.
