### ISSUE TITLE
As a user I would like to be able to see the road conditions so that I know if I can access a harvest area?

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#7]
Acceptance Criteria

- [ ] user can clearly see what roads are open or need special transport (chains)
- [ ] user can see when information was last updated
- [ ] user needs to know road conditions at the time permit is valid

Notes
- Forest Service employee must be able to update the data 

Tasks
- [ ] login for fs admin
- [ ] a forest service admin can't edit other forests they aren't authorized for

**Comment by rrefoy** [comment]
This needs to be split out to be forest specific. Marking this for backlog grooming on Wednesday.
