### ISSUE TITLE
As a user I need to be able to find information that is helpful to know around Christmas tree harvest in Mt. Hood.

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#94]
Acceptance criteria:
 - [ ] a user should be able to access and distinguish "nice to know" information from rules
 - [ ] a user can identify and navigate to a info section or the helpful information within a section

Definition of Done

 - [ ] Server Code unit / e2e tested and comply with QWASP
 - [ ] Frontend Code unit tested and comply with QWASP
 - [ ] Frontend Code e2e tested and comply with QWASP
 - [ ] No new security vulnerabilities
 - [ ] Team code review
 - [ ] Documentation / readme.md / CircleCI updated
 - [ ] Docker updated
 - [ ] Compare finished design with mockup if needed
 - [ ] Usability tested

Tasks

**Comment by lpendem** [comment]
@ASprinkle @JaneZC @lauraGgit The road numbers are displayed inconsistent across forest pages, can we standardize by adding `Road` to the ones that have only numbers?

**Comment by JaneZC** [comment]
@lpendem I believe some are roads and some are highways; I'll take a look and see if I can puzzle it out and make it clearer.

**Comment by sadlerw** [comment]
@ASprinkle I thought this story was done in a previous sprint? Do you remember why it is still open? @lauraGgit do you know?

**Comment by ASprinkle** [comment]
@sadlerw @lauraGgit If memory serves, we were going to add "roads" information.  During our last backlog refinement (epics sprint pointing) meeting I decided to get rid of the story for roads information and instead change it to add a "contact XX for up to date roads information" blurb.  In summary - this story should be closed, and I will edit the roads story.
