### ISSUE TITLE
As a user I want to be able to see illustrations so that I can quickly discover the information I need to know about Christmas tree harvesting in Mt. Hood Nat. Forest

### ISSUE THREAD

**Issue by sadlerw** [nciinc/fs-permit-platform#95]
Tasks
- [ ] Add graphics in the 'How to cut your tree' section that show stump height, stump diameter and tree height.

Acceptance Criteria

- [ ] user should be able to identify key information through illustrations 
- [ ] user should be able to tell that illustrations are clearly tied to specific rules or information
- [ ] user shouldn't have to see multiple styles of illustrations

**Comment by bryanmcfadden** [comment]
As an example:

![image](https://user-images.githubusercontent.com/16689692/32805648-0e05e768-c958-11e7-9e86-deb325b69071.png)

**Comment by ASprinkle** [comment]
Stories 428, 480, 479, 478 address this story.
